#-------------------------------
# General Site Settings
#-------------------------------
# Menu Section

menu:
- {title: Home, url: '#'}
- {title: Mod Mode, url: '/mod-mode'}
- {title: Live Streaam, url: '/live-stream/'}
menu-cta:
  title: Join Discord
  url: '#'

#-------------------------------
# Hero Section

hero:
  heeader: Home Of All Things JSL
  sub-header: Nothing but JSL

#-------------------------------
# Discord Section

discord:
  heeader: Check Out My Discord
  sub-header: Want to chat with me and meet my community members? Join today!
discord-button:
  title: JOIN DISCORD
  url: https://discord.gg/gAtK3q9

#-------------------------------
# About Section

about: I love computers and playing video games.. More to be added later :).

#-------------------------------
# SEO Section

seo:
  twitter-creator: '@example'
  twitter-site: '@example'
  type: 'website'
  google-analytics: UA-xxxx-1

#-------------------------------
# Social Icons and URls

social:
- {icon: 'fa-spotify', color: 'spotify-color', url: 'https://example.com'}

social-url:
  spotify: https://example.com

#-------------------------------
# Modified Date

modified-date: September 25, 2017

#-------------------------------
