#-------------------------------
# General Site Settings
#-------------------------------
# Menu Section

menu:
- {title: Home, url: '/'}
- {title: Mod Mode, url: '/mod-mode'}
- {title: Live Streaam, url: '/live-stream/'}

menu-cta:
  title: Join Discord
  url: 'https://discord.gg/UccND2w'

#-------------------------------
# Hero Section

hero:
  heeader: Home Of All Things JSL
  sub-header: Nothing but JSL

#-------------------------------
# Discord Section

discord:
  heeader: Check Out My Discord
  sub-header: Want to chat with me and meet my community members? Join today!

discord-button:
  title: JOIN DISCORD
  url: https://discord.gg/UccND2w

#-------------------------------
# About Section

about: I love computers and playing video games.. More to be added later :).

#-------------------------------
# Live Stream  Section

twitch-channel: jsl7

rules-panel:
  title: RULES
  rules:
    - {number: "1", rule: "No links unless you are given permission"}

streamers-panel:
  title: Awesome Streamers
  streamers:
    - {name: "tibbzeh" , url: "https://www.twitch.tv/tibbzeh"}
    - {name: "jonbams" , url: "https://www.twitch.tv/jonbams"}
    - {name: "darkosto" , url: "https://www.twitch.tv/darkosto"}
    - {name: "wyld" , url: "https://www.twitch.tv/wyld"}
    - {name: "ascothero" , url: "https://www.twitch.tv/ascothero"}
    - {name: "pitchit" , url: "https://www.twitch.tv/pitchit"}
    - {name: "supernuke4" , url: "https://www.twitch.tv/supernuke4"}

music-panel:
  title: Music
  music:
    - {image: "https://static-cdn.jtvnw.net/jtv_user_pictures/panel-54252779-image-e81ea45e0e71b5c2-320.png", title: "NoCopyrightSounds"}

#-------------------------------
# Mod Mode  Section

twitch_mod:
  - {channel: darkosto}
  - {channel: mrdemonwolf}
  - {channel: eltibbzo}

#-------------------------------
# SEO Section

seo:
  twitter-creator: '@mrdemonwolf'
  twitter-site: '@notjsl'
  type: 'website'
  google-analytics: UA-xxxx-1

#-------------------------------
# Social Icons and URls

social:
- {icon: 'fa-twitch', color: 'twitch-color', url: 'https://www.twitch.tv/jsl7'}
- {icon: 'fa-twitter', color: 'twitter-color', url: 'https://www.twitter.com/notjsl'}

social-url:
  spotify: https://example.com

#-------------------------------
# Modified Date

modified-date: September 25, 2017

#-------------------------------
